<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\NewDonationInfo;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Maatwebsite\Excel\Facades\Excel;

class NewDonationRequestTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testPostingTheNewDonationForm()
    {
        $this->assertEquals(0, NewDonationInfo::count());
        $data = factory(NewDonationInfo::class)->make([
            'email' => 'valid@gmail.com', //This mail will pass the dns check
            'phone_number' => '687462718', //Not all the numbers generated by faker match the regex
            'secondary_phone_number' => '967182729',
        ])->toArray();
        Excel::shouldReceive('store')->once();
        $response = $this->post('/donacion', $data);
        $response->assertViewIs('donacion-confirm');
        $this->assertEquals(1, NewDonationInfo::count());
        $this->assertEquals($data['full_name'], NewDonationInfo::first()->full_name);
    }
}
