<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\NewMemberInfo;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Maatwebsite\Excel\Facades\Excel;

class NewMemberRequestTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testPostingTheNewMemberForm()
    {
        $this->assertEquals(0, NewMemberInfo::count());
        $data = factory(NewMemberInfo::class)->make([
            'email' => 'valid@gmail.com', //This mail will pass the dns check
            'phone_number' => '687462718', //Not all the numbers generated by faker match the regex
            'secondary_phone_number' => '967182729',
            'passport_number' => 'ERT192392',
        ])->toArray();
        Excel::shouldReceive('store')->once();
        $response = $this->post('/socio', $data);
        $response->assertViewIs('socio-confirm');
        $this->assertEquals(1, NewMemberInfo::count());
        $this->assertEquals($data['full_name'], NewMemberInfo::first()->full_name);
    }
}
