<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\NewVolunteerInfo;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Maatwebsite\Excel\Facades\Excel;

class NewVolunteerRequestTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testPostingTheNewVolunteerForm()
    {
        $this->assertEquals(0, NewVolunteerInfo::count());
        $data = factory(NewVolunteerInfo::class)->make([
            'email' => 'valid@gmail.com', //This mail will pass the dns check
            'phone_number' => '687462718', //Not all the numbers generated by faker match the regex
            'secondary_phone_number' => '967182729',
            'passport_number' => 'ERT192392',
        ])->toArray();
        Excel::shouldReceive('store')->once();
        $response = $this->post('/voluntario', $data);
        $response->assertViewIs('voluntario-confirm');
        $this->assertEquals(1, NewVolunteerInfo::count());
        $this->assertEquals($data['full_name'], NewVolunteerInfo::first()->full_name);
    }
}
